language: python
python:
  - "2.7"
install:
  - make deps
script:
  - make test
  - make test_xunit
  - make lint
  - make docker_build
deploy:
  provider: heroku
  app: arcane-dusk-33275
  api_key: ${HEROKU_API_KEY}
